services:

  gotify-telegram:
    image: gotify-telegram-reflector
    container_name: gotify-telegram-reflector
    restart: unless-stopped
    environment:
      - GOTIFY_URL=gotify.server
      - GOTIFY_CLIENT_TOKEN=654321
      - TELEGRAM_CHAT_ID=123456
      - TELEGRAM_TOKEN=123456789:AAsdfgsdfg-SDFHsdfhsdfhdsfh